# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jing/squashfs-fuse

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jing/squashfs-fuse

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jing/squashfs-fuse/CMakeFiles /home/jing/squashfs-fuse//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jing/squashfs-fuse/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named squashfs-fuse

# Build rule for target.
squashfs-fuse: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 squashfs-fuse
.PHONY : squashfs-fuse

# fast build rule for target.
squashfs-fuse/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/squashfs-fuse.dir/build.make CMakeFiles/squashfs-fuse.dir/build
.PHONY : squashfs-fuse/fast

src/cache.o: src/cache.c.o
.PHONY : src/cache.o

# target to build an object file
src/cache.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/squashfs-fuse.dir/build.make CMakeFiles/squashfs-fuse.dir/src/cache.c.o
.PHONY : src/cache.c.o

src/cache.i: src/cache.c.i
.PHONY : src/cache.i

# target to preprocess a source file
src/cache.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/squashfs-fuse.dir/build.make CMakeFiles/squashfs-fuse.dir/src/cache.c.i
.PHONY : src/cache.c.i

src/cache.s: src/cache.c.s
.PHONY : src/cache.s

# target to generate assembly for a file
src/cache.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/squashfs-fuse.dir/build.make CMakeFiles/squashfs-fuse.dir/src/cache.c.s
.PHONY : src/cache.c.s

src/compressor.o: src/compressor.c.o
.PHONY : src/compressor.o

# target to build an object file
src/compressor.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/squashfs-fuse.dir/build.make CMakeFiles/squashfs-fuse.dir/src/compressor.c.o
.PHONY : src/compressor.c.o

src/compressor.i: src/compressor.c.i
.PHONY : src/compressor.i

# target to preprocess a source file
src/compressor.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/squashfs-fuse.dir/build.make CMakeFiles/squashfs-fuse.dir/src/compressor.c.i
.PHONY : src/compressor.c.i

src/compressor.s: src/compressor.c.s
.PHONY : src/compressor.s

# target to generate assembly for a file
src/compressor.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/squashfs-fuse.dir/build.make CMakeFiles/squashfs-fuse.dir/src/compressor.c.s
.PHONY : src/compressor.c.s

src/data.o: src/data.c.o
.PHONY : src/data.o

# target to build an object file
src/data.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/squashfs-fuse.dir/build.make CMakeFiles/squashfs-fuse.dir/src/data.c.o
.PHONY : src/data.c.o

src/data.i: src/data.c.i
.PHONY : src/data.i

# target to preprocess a source file
src/data.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/squashfs-fuse.dir/build.make CMakeFiles/squashfs-fuse.dir/src/data.c.i
.PHONY : src/data.c.i

src/data.s: src/data.c.s
.PHONY : src/data.s

# target to generate assembly for a file
src/data.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/squashfs-fuse.dir/build.make CMakeFiles/squashfs-fuse.dir/src/data.c.s
.PHONY : src/data.c.s

src/directory.o: src/directory.c.o
.PHONY : src/directory.o

# target to build an object file
src/directory.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/squashfs-fuse.dir/build.make CMakeFiles/squashfs-fuse.dir/src/directory.c.o
.PHONY : src/directory.c.o

src/directory.i: src/directory.c.i
.PHONY : src/directory.i

# target to preprocess a source file
src/directory.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/squashfs-fuse.dir/build.make CMakeFiles/squashfs-fuse.dir/src/directory.c.i
.PHONY : src/directory.c.i

src/directory.s: src/directory.c.s
.PHONY : src/directory.s

# target to generate assembly for a file
src/directory.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/squashfs-fuse.dir/build.make CMakeFiles/squashfs-fuse.dir/src/directory.c.s
.PHONY : src/directory.c.s

src/fragment.o: src/fragment.c.o
.PHONY : src/fragment.o

# target to build an object file
src/fragment.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/squashfs-fuse.dir/build.make CMakeFiles/squashfs-fuse.dir/src/fragment.c.o
.PHONY : src/fragment.c.o

src/fragment.i: src/fragment.c.i
.PHONY : src/fragment.i

# target to preprocess a source file
src/fragment.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/squashfs-fuse.dir/build.make CMakeFiles/squashfs-fuse.dir/src/fragment.c.i
.PHONY : src/fragment.c.i

src/fragment.s: src/fragment.c.s
.PHONY : src/fragment.s

# target to generate assembly for a file
src/fragment.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/squashfs-fuse.dir/build.make CMakeFiles/squashfs-fuse.dir/src/fragment.c.s
.PHONY : src/fragment.c.s

src/inode.o: src/inode.c.o
.PHONY : src/inode.o

# target to build an object file
src/inode.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/squashfs-fuse.dir/build.make CMakeFiles/squashfs-fuse.dir/src/inode.c.o
.PHONY : src/inode.c.o

src/inode.i: src/inode.c.i
.PHONY : src/inode.i

# target to preprocess a source file
src/inode.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/squashfs-fuse.dir/build.make CMakeFiles/squashfs-fuse.dir/src/inode.c.i
.PHONY : src/inode.c.i

src/inode.s: src/inode.c.s
.PHONY : src/inode.s

# target to generate assembly for a file
src/inode.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/squashfs-fuse.dir/build.make CMakeFiles/squashfs-fuse.dir/src/inode.c.s
.PHONY : src/inode.c.s

src/log.o: src/log.c.o
.PHONY : src/log.o

# target to build an object file
src/log.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/squashfs-fuse.dir/build.make CMakeFiles/squashfs-fuse.dir/src/log.c.o
.PHONY : src/log.c.o

src/log.i: src/log.c.i
.PHONY : src/log.i

# target to preprocess a source file
src/log.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/squashfs-fuse.dir/build.make CMakeFiles/squashfs-fuse.dir/src/log.c.i
.PHONY : src/log.c.i

src/log.s: src/log.c.s
.PHONY : src/log.s

# target to generate assembly for a file
src/log.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/squashfs-fuse.dir/build.make CMakeFiles/squashfs-fuse.dir/src/log.c.s
.PHONY : src/log.c.s

src/main.o: src/main.c.o
.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/squashfs-fuse.dir/build.make CMakeFiles/squashfs-fuse.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/squashfs-fuse.dir/build.make CMakeFiles/squashfs-fuse.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/squashfs-fuse.dir/build.make CMakeFiles/squashfs-fuse.dir/src/main.c.s
.PHONY : src/main.c.s

src/stats.o: src/stats.c.o
.PHONY : src/stats.o

# target to build an object file
src/stats.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/squashfs-fuse.dir/build.make CMakeFiles/squashfs-fuse.dir/src/stats.c.o
.PHONY : src/stats.c.o

src/stats.i: src/stats.c.i
.PHONY : src/stats.i

# target to preprocess a source file
src/stats.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/squashfs-fuse.dir/build.make CMakeFiles/squashfs-fuse.dir/src/stats.c.i
.PHONY : src/stats.c.i

src/stats.s: src/stats.c.s
.PHONY : src/stats.s

# target to generate assembly for a file
src/stats.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/squashfs-fuse.dir/build.make CMakeFiles/squashfs-fuse.dir/src/stats.c.s
.PHONY : src/stats.c.s

src/superblock.o: src/superblock.c.o
.PHONY : src/superblock.o

# target to build an object file
src/superblock.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/squashfs-fuse.dir/build.make CMakeFiles/squashfs-fuse.dir/src/superblock.c.o
.PHONY : src/superblock.c.o

src/superblock.i: src/superblock.c.i
.PHONY : src/superblock.i

# target to preprocess a source file
src/superblock.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/squashfs-fuse.dir/build.make CMakeFiles/squashfs-fuse.dir/src/superblock.c.i
.PHONY : src/superblock.c.i

src/superblock.s: src/superblock.c.s
.PHONY : src/superblock.s

# target to generate assembly for a file
src/superblock.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/squashfs-fuse.dir/build.make CMakeFiles/squashfs-fuse.dir/src/superblock.c.s
.PHONY : src/superblock.c.s

src/utils.o: src/utils.c.o
.PHONY : src/utils.o

# target to build an object file
src/utils.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/squashfs-fuse.dir/build.make CMakeFiles/squashfs-fuse.dir/src/utils.c.o
.PHONY : src/utils.c.o

src/utils.i: src/utils.c.i
.PHONY : src/utils.i

# target to preprocess a source file
src/utils.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/squashfs-fuse.dir/build.make CMakeFiles/squashfs-fuse.dir/src/utils.c.i
.PHONY : src/utils.c.i

src/utils.s: src/utils.c.s
.PHONY : src/utils.s

# target to generate assembly for a file
src/utils.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/squashfs-fuse.dir/build.make CMakeFiles/squashfs-fuse.dir/src/utils.c.s
.PHONY : src/utils.c.s

src/xattr.o: src/xattr.c.o
.PHONY : src/xattr.o

# target to build an object file
src/xattr.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/squashfs-fuse.dir/build.make CMakeFiles/squashfs-fuse.dir/src/xattr.c.o
.PHONY : src/xattr.c.o

src/xattr.i: src/xattr.c.i
.PHONY : src/xattr.i

# target to preprocess a source file
src/xattr.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/squashfs-fuse.dir/build.make CMakeFiles/squashfs-fuse.dir/src/xattr.c.i
.PHONY : src/xattr.c.i

src/xattr.s: src/xattr.c.s
.PHONY : src/xattr.s

# target to generate assembly for a file
src/xattr.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/squashfs-fuse.dir/build.make CMakeFiles/squashfs-fuse.dir/src/xattr.c.s
.PHONY : src/xattr.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... squashfs-fuse"
	@echo "... src/cache.o"
	@echo "... src/cache.i"
	@echo "... src/cache.s"
	@echo "... src/compressor.o"
	@echo "... src/compressor.i"
	@echo "... src/compressor.s"
	@echo "... src/data.o"
	@echo "... src/data.i"
	@echo "... src/data.s"
	@echo "... src/directory.o"
	@echo "... src/directory.i"
	@echo "... src/directory.s"
	@echo "... src/fragment.o"
	@echo "... src/fragment.i"
	@echo "... src/fragment.s"
	@echo "... src/inode.o"
	@echo "... src/inode.i"
	@echo "... src/inode.s"
	@echo "... src/log.o"
	@echo "... src/log.i"
	@echo "... src/log.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/stats.o"
	@echo "... src/stats.i"
	@echo "... src/stats.s"
	@echo "... src/superblock.o"
	@echo "... src/superblock.i"
	@echo "... src/superblock.s"
	@echo "... src/utils.o"
	@echo "... src/utils.i"
	@echo "... src/utils.s"
	@echo "... src/xattr.o"
	@echo "... src/xattr.i"
	@echo "... src/xattr.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

